# Generated by Django 6.0.2 on 2026-02-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('student', 'Student'), ('university', 'University')], max_length=20, null=True),
        ),
    ]
