services:
  db:
    image: postgres:16-alpine
    container_name: django_db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mararmurray_network
  
  # --- REDIS ADDED ---
  redis:
    image: redis:7-alpine
    container_name: django_redis
    restart: always
    networks:
      - mararmurray_network

  django_app:
    image: sadiyairin/mararmurray:latest
    container_name: django_app
    restart: always
    expose:
      - "8005"
    env_file: .env
    depends_on:
      - db
      - redis # Redis এর ওপর নির্ভর করবে
    volumes:
     # - .:/app
      - ./static:/app/static
      - ./media:/app/media
   # working_dir: /app
    command: python -m uvicorn core.asgi:application --host 0.0.0.0 --port 8005
    networks:
      - mararmurray_network #Docker network for inter-container communication

  
  # --- CELERY WORKER ADDED ---
  celery_worker:
    image: sadiyairin/mararmurray:latest # একই ইমেজ ব্যবহার করবে
    container_name: celery_worker
    restart: always
    env_file: .env
    volumes:
      - ./media:/app/media # ইমেজ সেভ করার জন্য মিডিয়া ভলিউম জরুরি
    # আপনার প্রোজেক্টের নাম 'core' হলে কমান্ডটি এমন হবে
    command: celery -A core worker --loglevel=info 
    depends_on:
      - db
      - redis
      - django_app
    networks:
      - mararmurray_network
      
  # --- CELERY BEAT ADDED ---
  celery_beat:
    image: sadiyairin/mararmurray:latest
    container_name: celery_beat
    restart: always
    env_file: .env
    command: celery -A core beat --loglevel=info
    depends_on:
      - db
      - redis
      - django_app
    networks:
      - mararmurray_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./static:/app/static:ro
      - ./media:/app/media:ro
    depends_on:
      - django_app
    networks:
      - mararmurray_network

networks:
  mararmurray_network:
    driver: bridge

volumes:
  postgres_data: # এই ভলিউমটি আপনার ডেটাবেস পারসিস্টেন্ট রাখবে
