# --- HTTP থেকে HTTPS Redirect ---
server {
    listen 80;
    server_name api.florle.com;
    return 301 https://$host$request_uri;
}

# ---- Backend API (api.florle.com) ----
server {
    listen 443 ssl;
    server_name api.florle.com;
   
   client_max_body_size 100M;

    # SSL সার্টিফিকেট পাথ (নিশ্চিত করুন এই ডোমেইনের জন্য SSL জেনারেট করা আছে)
    ssl_certificate /etc/letsencrypt/live/api.florle.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.florle.com/privkey.pem;

    # API রিকোয়েস্ট হ্যান্ডেল করার জন্য
    location / {
        proxy_pass http://django_app:8005;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;


	# --- HIGHLIGHT: TIMEOUT SETTINGS ADDED ---
        proxy_read_timeout 300; # ৩০০ সেকেন্ড বা ৫ মিনিট অপেক্ষা করবে
        proxy_connect_timeout 300;
        proxy_send_timeout 300;
    }

    # জ্যাঙ্গো অ্যাডমিন প্যানেল বা স্ট্যাটিক ফাইলের জন্য
    location /static/ {
        alias /app/static/;
    }

    # ইউজার আপলোড করা মিডিয়া ফাইলের জন্য (যদি থাকে)
    location /media/ { 
        alias /app/media/; 
        client_max_body_size 20M; # বড় ফাইল আপলোডের জন্য
    }
}
