# Generated by Django 6.0.2 on 2026-03-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_gardenproject_gardenpreference_gardenphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenphoto',
            name='quality_score',
            field=models.IntegerField(default=0, help_text='Quality score from 0-100'),
        ),
        migrations.AlterField(
            model_name='gardenphoto',
            name='quality_issues',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
