# Generated by Django 6.0.2 on 2026-03-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_gardenphoto_quality_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gardenpreference',
            name='project',
        ),
        migrations.RemoveField(
            model_name='gardenproject',
            name='user',
        ),
        migrations.DeleteModel(
            name='GardenPhoto',
        ),
        migrations.DeleteModel(
            name='GardenPreference',
        ),
        migrations.DeleteModel(
            name='GardenProject',
        ),
    ]
