# Generated by Django 6.0.2 on 2026-03-11 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0005_plant_garden_type_plant_soil_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Garden', max_length=255)),
                ('garden_image_url', models.URLField(max_length=1000)),
                ('blended_image', models.ImageField(blank=True, null=True, upload_to='garden_compositions/')),
                ('composite_image', models.ImageField(blank=True, null=True, upload_to='garden_composites/')),
                ('revised_prompt', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GardenPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0.5, help_text='Relative X position (0.0 – 1.0)')),
                ('y', models.FloatField(default=0.5, help_text='Relative Y position (0.0 – 1.0)')),
                ('scale', models.FloatField(default=1.0, help_text='Scale factor (1.0 = natural size)')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_plants', to='gardens.garden')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_appearances', to='plants.plant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
