# Generated by Django 6.0.2 on 2026-03-11 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GardenPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, help_text='City, zip code, or coordinates', max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('sunlight', models.CharField(blank=True, choices=[('full_sun', 'Full Sun (6+ hours)'), ('partial_sun', 'Partial Sun (3-6 hours)'), ('full_shade', 'Full Shade (<3 hours)')], max_length=20, null=True)),
                ('soil_type', models.CharField(blank=True, choices=[('sandy', 'Sandy'), ('clay', 'Clay'), ('loam', 'Loam'), ('not_sure', 'Not Sure')], max_length=20, null=True)),
                ('garden_type', models.CharField(blank=True, choices=[('flower', 'Flower Garden'), ('vegetable', 'Vegetable Garden'), ('herb', 'Herb Garden'), ('mixed', 'Mixed Garden')], max_length=20, null=True)),
                ('total_area_sq_ft', models.FloatField(blank=True, help_text='Total area in square feet', null=True)),
                ('height_ft', models.FloatField(blank=True, help_text='Height in feet', null=True)),
                ('width_ft', models.FloatField(blank=True, help_text='Width in feet', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garden_preference', to='gardens.gardenproject')),
            ],
        ),
        migrations.CreateModel(
            name='GardenPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='garden_photos/')),
                ('quality_status', models.CharField(choices=[('good', 'Good'), ('poor', 'Poor'), ('pending', 'Pending Analysis')], default='pending', max_length=20)),
                ('quality_score', models.IntegerField(default=0, help_text='Quality score from 0-100')),
                ('quality_issues', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garden_photo', to='gardens.gardenproject')),
            ],
        ),
    ]
