# Generated by Django 6.0.2 on 2026-03-12 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_gardenproject_gardenpreference_gardenphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gardenplant',
            name='garden',
        ),
        migrations.RemoveField(
            model_name='gardenplant',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='gardenpreference',
            name='project',
        ),
        migrations.AlterModelOptions(
            name='gardenproject',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='gardenphoto',
            name='project',
        ),
        migrations.AddField(
            model_name='gardenphoto',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garden_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gardenproject',
            name='blended_image',
            field=models.ImageField(blank=True, help_text='Final AI-blended garden image', null=True, upload_to='garden_compositions/'),
        ),
        migrations.AddField(
            model_name='gardenproject',
            name='composite_image',
            field=models.ImageField(blank=True, help_text='Pre-AI composite (overlay) image', null=True, upload_to='garden_composites/'),
        ),
        migrations.AddField(
            model_name='gardenproject',
            name='garden_type',
            field=models.CharField(blank=True, choices=[('flower', 'Flower Garden'), ('vegetable', 'Vegetable Garden'), ('herb', 'Herb Garden'), ('mixed', 'Mixed Garden')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gardenproject',
            name='height_ft',
            field=models.FloatField(blank=True, help_text='Garden height in feet', null=True),
        ),
        migrations.AddField(
            model_name='gardenproject',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gardenproject',
            name='location',
            field=models.CharField(blank=True, help_text='City, zip code, or coordinates', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gardenproject',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gardenproject',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='gardens.gardenphoto'),
        ),
        migrations.AddField(
            model_name='gardenproject',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('sandy', 'Sandy'), ('clay', 'Clay'), ('loam', 'Loam'), ('not_sure', 'Not Sure')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gardenproject',
            name='sunlight',
            field=models.CharField(blank=True, choices=[('full_sun', 'Full Sun (6+ hours)'), ('partial_sun', 'Partial Sun (3–6 hours)'), ('full_shade', 'Full Shade (<3 hours)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gardenproject',
            name='total_area_sq_ft',
            field=models.FloatField(blank=True, help_text='Total garden area in sq ft', null=True),
        ),
        migrations.AddField(
            model_name='gardenproject',
            name='width_ft',
            field=models.FloatField(blank=True, help_text='Garden width in feet', null=True),
        ),
        migrations.AlterField(
            model_name='gardenphoto',
            name='quality_score',
            field=models.IntegerField(default=0, help_text='Quality score 0–100'),
        ),
        migrations.AlterField(
            model_name='gardenproject',
            name='name',
            field=models.CharField(default='My Garden', max_length=255),
        ),
        migrations.DeleteModel(
            name='Garden',
        ),
        migrations.DeleteModel(
            name='GardenPlant',
        ),
        migrations.DeleteModel(
            name='GardenPreference',
        ),
    ]
