# Generated by Django 6.0.2 on 2026-03-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0003_remove_gardenplant_garden_remove_gardenplant_plant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenproject',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='garden_photos/'),
        ),
    ]
