# Generated by Django 6.0.2 on 2026-03-12 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0004_alter_gardenproject_photo'),
        ('plants', '0007_alter_plant_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0.5, help_text='Relative X position (0.0–1.0)')),
                ('y', models.FloatField(default=0.5, help_text='Relative Y position (0.0–1.0)')),
                ('scale', models.FloatField(default=1.0, help_text='Scale factor (1.0 = natural size)')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_appearances', to='plants.plant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='gardens.gardenproject')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
