# Generated by Django 6.0.2 on 2026-04-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0005_gardenplant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenproject',
            name='garden_type',
            field=models.CharField(blank=True, choices=[('flower_garden', 'Flower Garden'), ('vegetable_garden', 'Vegetable Garden'), ('herb_garden', 'Herb Garden'), ('mixed_garden', 'Mixed Garden')], max_length=20, null=True),
        ),
    ]
