from django.urls import path

from apps.accounts.views import (
    change_password,
    delete_account,
    delete_user_image,
    get_profile,
    get_user_image,
    logout,
    password_reset,
    send_otp,
    signin,
    signup,
    upload_user_image,
    user_activate,
    user_deactivate,
    user_delete,
    user_detail,
    user_edit,
    user_update,
    users,
    verify_otp,
)

urlpatterns = [
    path("signup/", signup, name="signup"),
    path("signin/", signin, name="signin"),
    path("send-otp/", send_otp, name="send_otp"),
    path("verify-otp/", verify_otp, name="verify_otp"),
    path("reset-password/", password_reset, name="password_reset"),
    path("change-password/", change_password, name="change_password"),
    path("profile/", get_profile, name="get-profile"),
    path("users/", users, name="users"),  # Admin users list (page, limit, search)
    path("user/detail/<int:user_id>/", user_detail, name="user_detail"),
    path("users/<int:user_id>/edit/", user_edit, name="user_edit"),
    path("users/<int:user_id>/deactivate/", user_deactivate, name="user_deactivate"),
    path("users/<int:user_id>/activate/", user_activate, name="user_activate"),
    path("users/<int:user_id>/delete/", user_delete, name="user_delete"),
    path("user/edit/", user_update, name="user_update"),
    path("logout/", logout, name="logout"),
    path("delete-account/", delete_account, name="delete_account"),
    path("profile/image/upload/", upload_user_image, name="upload-user-image"),
    path("profile/image/", get_user_image, name="get-user-image"),
    path("profile/image/delete/", delete_user_image, name="delete-user-image"),
]
