# Generated by Django 6.0.2 on 2026-03-17 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0005_gardenplant'),
        ('posts', '0004_savedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='garden_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='gardens.gardenproject'),
        ),
    ]
