# Generated by Django 6.0.2 on 2026-03-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_garden_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('flagged', 'Flagged')], default='published', max_length=20),
        ),
    ]
