# Generated by Django 6.0.2 on 2026-02-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(max_length=255)),
                ('plant_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('main_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('sunlight', models.CharField(max_length=100)),
                ('water', models.CharField(max_length=255)),
                ('spacing', models.CharField(blank=True, max_length=100, null=True)),
                ('growth_size', models.CharField(blank=True, max_length=100, null=True)),
                ('season', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=100, null=True)),
                ('care_guide', models.TextField(blank=True, null=True)),
                ('bloom_spring', models.BooleanField(default=False)),
                ('bloom_summer', models.BooleanField(default=False)),
                ('bloom_fall', models.BooleanField(default=False)),
                ('bloom_winter', models.BooleanField(default=False)),
                ('shopping_link', models.URLField(blank=True, max_length=500, null=True)),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags', null=True)),
                ('family', models.CharField(blank=True, max_length=100, null=True)),
                ('propagation', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
