# Generated by Django 6.0.2 on 2026-02-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='water',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
