# Generated by Django 6.0.2 on 2026-03-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_plant_water'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='plant_images/'),
        ),
    ]
