# Generated by Django 6.0.2 on 2026-03-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plant_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='images',
            new_name='image',
        ),
    ]
