# Generated by Django 6.0.2 on 2026-03-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_plant_garden_type_plant_soil_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('sandy', 'Sandy'), ('clay', 'Clay'), ('loam', 'Loam'), ('not_sure', 'Not Sure')], default='loam', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sunlight',
            field=models.CharField(choices=[('full_sun', 'Full Sun'), ('partial_sun', 'Partial Sun'), ('full_shade', 'Full Shade')], default='full_sun', max_length=100),
        ),
    ]
