# Generated by Django 6.0.2 on 2026-03-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_alter_plant_soil_type_alter_plant_sunlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='difficulty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
