# Generated by Django 6.0.2 on 2026-03-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0007_alter_plant_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="plant_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("annual", "Annual"),
                    ("perenial", "Perenial"),
                    ("both", "Both"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
