# Generated by Django 6.0.2 on 2026-04-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_alter_plant_plant_type_add_plant_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(blank=True, choices=[('annual', 'Annual'), ('perenial', 'Perenial'), ('both', 'Both')], max_length=200, null=True),
        ),
    ]
