# Generated by Django 6.0.2 on 2026-04-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_alter_plant_plant_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_processed_page', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
