# Generated by Django 6.0.2 on 2026-04-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_harvestmetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='main_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
