# Generated by Django 6.0.2 on 2026-04-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0011_alter_plant_main_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='main_image_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
    ]
